#!/usr/bin/env bash

set -eu

opencode_bin=$(which opencode)
host_cargo_home="${CARGO_HOME:-$HOME/.cargo/}"
host_rustup_home="${RUSTUP_HOME:-$HOME/.rustup}"
host_npm_local_home="${NPM_LOCAL_HOME:-$HOME/.npm-packages}"

  #--unshare-all \

bwrap \
  --unshare-pid \
  --unshare-uts \
  --unshare-ipc \
  --share-net \
  --new-session \
  --die-with-parent \
  --ro-bind /usr /usr \
  --ro-bind /lib /lib \
  --ro-bind-try /lib64 /lib64 \
  --ro-bind /bin /bin \
  --ro-bind /etc /etc \
  --ro-bind /run /run \
  --tmpfs /tmp \
  --dev   /dev \
  --proc  /proc \
  --bind "$HOME/.config/opencode" "$HOME/.config/opencode" \
  --bind "$HOME/.local/share/opencode" "$HOME/.local/share/opencode" \
  --bind "$HOME/.local/state/opencode" "$HOME/.local/state/opencode" \
  --bind "$HOME/.cache/opencode" "$HOME/.cache/opencode" \
  --ro-bind "$host_rustup_home" "$host_rustup_home" \
  --bind    "$host_cargo_home"  "$host_cargo_home" \
  --ro-bind "$host_npm_local_home" "$host_npm_local_home" \
  --ro-bind "$SHELL" "$SHELL" \
  --setenv  SHELL "$SHELL" \
  --setenv  EDITOR "vim" \
  --bind "$PWD" "$PWD" \
  "$opencode_bin" "$@"
